<a href="https://colab.research.google.com/github/saeekundikar/smart-campus-intelligence/blob/main/srishti.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
df_elec= pd.read_csv('/content/household_power_consumption.csv.zip')

In [22]:
df_elec.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0,1,17.0
1,16/12/2006,17:25:00,5.36,0.436,233.63,23,0,1,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23,0,2,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23,0,1,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0,1,17.0

In [23]:
df_elec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Date                   1048575 non-null  object
 1   Time                   1048575 non-null  object
 2   Global_active_power    1048575 non-null  object
 3   Global_reactive_power  1048575 non-null  object
 4   Voltage                1048575 non-null  object
 5   Global_intensity       1048575 non-null  object
 6   Sub_metering_1         1048575 non-null  object
 7   Sub_metering_2         1048575 non-null  object
 8   Sub_metering_3         1044506 non-null  float64
dtypes: float64(1), object(8)
memory usage: 72.0+ MB

In [24]:
df_elec.replace('?', np.nan, inplace=True)
df_elec.dropna(inplace=True)

In [25]:
df_elec['timestamp'] = pd.to_datetime(df_elec['Date'] + ' ' + df_elec['Time'])

/tmp/ipykernel_9183/70452921.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_elec['timestamp'] = pd.to_datetime(df_elec['Date'] + ' ' + df_elec['Time'])

 Keep only important column

In [27]:


df_elec = df_elec[['timestamp', 'Global_active_power']]
df_elec.rename(columns={'Global_active_power': 'electricity_usage'}, inplace=True)

Convert to float

In [28]:

df_elec['electricity_usage'] = df_elec['electricity_usage'].astype(float)

Save clean electricity data

In [29]:

df_elec.to_csv("electricity_data.csv", index=False)

In [30]:

print("✅ Electricity dataset ready")

✅ Electricity dataset ready

In [31]:
df_elec.head()

            timestamp  electricity_usage
0 2006-12-16 17:24:00              4.216
1 2006-12-16 17:25:00              5.360
2 2006-12-16 17:26:00              5.374
3 2006-12-16 17:27:00              5.388
4 2006-12-16 17:28:00              3.666